[package]
name = "memchr-n"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
authors = ["Zachary Dremann <dremann@gmail.com>"]
description = "Fast SIMD-accelerated search and iteration over the bytes belonging to an arbitrary set of byte values"
repository = "https://github.com/Dr-Emann/memchr_n"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["memchr", "simd", "search", "bytes", "scan"]
categories = ["algorithms", "text-processing"]

[dependencies]
